# Generated by Django 5.0.1 on 2024-02-03 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(blank=True)),
                ('posted_date', models.DateField(blank=True)),
                ('description', models.CharField(default='', max_length=150)),
                ('category', models.TextField(blank=True, default='')),
                ('category_certainty', models.FloatField(blank=True, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager.account')),
            ],
        ),
    ]
