# Generated by Django 5.0.1 on 2024-02-09 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('account_manager', '0002_checkingaccount_creditcardaccount_and_more'), ('account_manager', '0003_transaction_balance'), ('account_manager', '0004_alter_transaction_balance')]

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account_manager.account')),
            ],
            bases=('account_manager.account',),
        ),
        migrations.CreateModel(
            name='CreditCardAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account_manager.account')),
            ],
            bases=('account_manager.account',),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account_manager.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True),
        ),
    ]
