# Generated by Django 5.0.1 on 2024-02-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0003_transaction_tags_transactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
