# Generated by Django 5.0.1 on 2024-02-17 06:02

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('account_manager', '0005_alter_transaction_tags_and_more'), ('account_manager', '0006_alter_transaction_category_and_more'), ('account_manager', '0007_alter_transactionitem_category_and_more'), ('account_manager', '0008_transactionitem__itemized_from')]

    dependencies = [
        ('account_manager', '0004_transaction_note'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='_itemized_from',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_manager.transactionitem'),
        ),
    ]
