# Generated by Django 5.0.1 on 2024-02-17 21:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0005_alter_transaction_tags_and_more_squashed_0008_transactionitem__itemized_from'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Lower('category'), descending=True), name='category_name_lower_idx'),
        ),
    ]
