# Generated by Django 5.0.1 on 2024-02-19 02:55

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0009_transaction_category_name_lower_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='category_certainty',
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor_certainty',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_certainty',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
