# Generated by Django 5.0.1 on 2024-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getvendor_aimodel',
            name='model',
            field=models.CharField(choices=[('llama2:7b-text', 'llama2:7b-text')], max_length=255, unique=True),
        ),
    ]
