# Generated by Django 5.0.1 on 2024-02-18 20:40

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manager', '0003_getvendor_aimodel_input_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='getvendor_aimodel',
            name='db',
            field=models.FilePathField(blank=True, default='', verbose_name=pathlib.PurePosixPath('/home/danny/Programming/expense_tracker/expense_tracker')),
        ),
    ]
