# Generated by Django 5.0.1 on 2024-02-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manager', '0004_getvendor_aimodel_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getvendor_aimodel',
            name='db',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
